# Creating the mongodb PVC

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
      
# Creating the mongodb service   

--- 
# Select the type of API version and type of service/object
apiVersion: v1
kind: Service

# Metadata for name
metadata:
  name: mongodb-svc
  namespace: default #sre
# Specification to include ports Selector to connect to the ?
spec:
  ports:
   # expose the ports
  - port: 27017


    targetPort: 27017

  # lets define the selector and label to connect to nginx deploment
  selector:
    app: mongodb 


# Creating the mongodb deployment

---
apiVersion: apps/v1 # which api to use for deployment

kind: Deployment # what kind of service/object do you want to create?

# what would you like to call it - name the service/object


metadata:
  name: mongodb
spec:
  selector: 
    matchLabels:
      app: mongodb
  replicas: 3

  template:
    metadata:
      labels:
        app: mongodb
    
    spec: 
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: storage
          mountPath: /data/db

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: mongo-pvc





