# Select the type of API version and type of service/object
apiVersion: v1
kind: Service

# Metadata for name
metadata:
  name: mongodb-svc
  namespace: default #sre
# Specification to include ports Selector to connect to the ?
spec:
  ports:
   # expose the ports
  - port: 27017


    targetPort: 27017

  # lets define the selector and label to connect to nginx deploment
  selector:
    app: mongodb 